# Generated by Django 2.0.2 on 2018-03-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180304_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('POLITICS', 'POLITICS'), ('TECH', 'TECH'),
                                            ('SCIENCE', 'SCIENCE'), ('SPORTS', 'SPORTS'),
                                            ('BUSINESS', 'BUSINESS')], max_length=128),
        ),
    ]
