# Generated by Django 2.0.2 on 2018-03-04 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_preferences', '__first__'),
        ('news', '0003_auto_20180304_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_preferences.Profile'),
        ),
    ]
