# Generated by Django 2.0.2 on 2018-03-08 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20180307_0409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='picture',
            name='news',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail', to='news.News'),
        ),
    ]
