# Generated by Django 2.0.2 on 2018-03-07 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_preferences', '0002_auto_20180304_0446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='categories',
            field=models.ManyToManyField(related_name='profiles', to='user_preferences.Category'),
        ),
    ]
