# Generated by Django 2.0.2 on 2018-03-08 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_preferences', '0005_auto_20180308_0350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='profile',
            new_name='user',
        ),
    ]
