# Generated by Django 2.0.2 on 2018-03-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_preferences', '0007_category_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='big',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='small',
            field=models.CharField(max_length=32),
        ),
    ]
