export const REQUEST_NEWS = 'REQUEST_NEWS'
export const RECEIVE_NEWS = 'RECEIVE_NEWS'
export const RECEIVE_NEWS_ERROR = 'RECEIVE_NEWS_ERROR'

export const REQUEST_CATEGORIES = 'REQUEST_CATEGORIES'
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES'
export const RECEIVE_CATEGORIES_ERROR = 'RECEIVE_CATEGORIES_ERROR'

export const REQUEST_USER = 'REQUEST_USER'
export const RECEIVE_USER = 'RECEIVE_USER'
export const RECEIVE_USER_ERROR = 'RECEIVE_USER_ERROR'
export const REQUEST_CHANGE_USER_PREFERENCES = 'REQUEST_CHANGE_USER_PREFERENCES'
export const RECEIVE_USER_PREFERENCES = 'RECEIVE_USER_PREFERENCES'

export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
