export const REQUEST_NEWS = 'REQUEST_NEWS'
export const RECEIVE_NEWS = 'RECEIVE_NEWS'
export const RECEIVE_NEWS_ERROR = 'RECEIVE_NEWS_ERROR'

export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'

export const CHANGE_USER_PREFERENCE = 'CHANGE_USER_PREFERENCE'