export const REQUEST_NEWS = 'REQUEST_NEWS'
export const RECEIVE_NEWS = 'RECEIVE_NEWS'
export const RECEIVE_NEWS_ERROR = 'RECEIVE_NEWS_ERROR'

export const REQUEST_CATEGORIES = 'REQUEST_CATEGORIES'
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES'
export const RECEIVE_CATEGORIES_ERROR = 'RECEIVE_CATEGORIES_ERROR'

export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'

export const CHANGE_USER_PREFERENCE = 'CHANGE_USER_PREFERENCE'
